const objectFields = {
  Account: [
    "Id",
    "Name",
    "Phone",
    "Website",
    "Industry",
    "Type",
    "Rating",
    "AnnualRevenue",
    "NumberOfEmployees",
    "BillingStreet",
    "BillingCity",
    "BillingState",
    "BillingPostalCode",
    "BillingCountry",
    "Description",
  ],

  Contact: [
    "Id",
    "FirstName",
    "LastName",
    "Email",
    "Phone",
    "MobilePhone",
    "Title",
    "Department",
    "AccountId",
    "LeadSource",
    "Birthdate",
    "MailingStreet",
    "MailingCity",
    "MailingState",
    "MailingPostalCode",
    "MailingCountry",
    "Description",
  ],

  Lead: [
    "Id",
    "FirstName",
    "LastName",
    "Email",
    "Company",
    "Phone",
    "MobilePhone",
    "Title",
    "Industry",
    "LeadSource",
    "Status",
    "Rating",
    "AnnualRevenue",
    "NumberOfEmployees",
    "Website",
    "Street",
    "City",
    "State",
    "PostalCode",
    "Country",
    "Description",
  ],

  Opportunity: [
    "Id",
    "Name",
    "Amount",
    "StageName",
    "CloseDate",
    "Probability",
    "Type",
    "LeadSource",
  ],

  Case: [
    "Id",
    "CaseNumber",
    "Subject",
    "Status",
    "Priority",
    "Origin",
    "Type",
    "AccountId",
    "ContactId",
  ],
};

module.exports = {
  objectFields,
};
